CREATE TABLE CARSHARE (
  PRIMARY KEY (UID),
  UID             VARCHAR(42) NOT NULL,
  max_passenger   VARCHAR(42),
  is_Full         VARCHAR(42),
  schedule        VARCHAR(42),
  start_place     VARCHAR(42),
  end_place       VARCHAR(42),
  distance        VARCHAR(42),
  bonus_pollution VARCHAR(42),
  UID_driver      VARCHAR(42) NOT NULL
);

CREATE TABLE CHALLENGE (
  PRIMARY KEY (UID),
  UID          VARCHAR(42) NOT NULL,
  name         VARCHAR(42),
  description  VARCHAR(42),
  bonus_exp    VARCHAR(42),
  expired_date VARCHAR(42)
);

CREATE TABLE COMPANY (
  PRIMARY KEY (UID),
  UID  VARCHAR(42) NOT NULL,
  name VARCHAR(42)
);

CREATE TABLE ISPASSENGER (
  PRIMARY KEY (UID, UID_passegenr),
  UID           VARCHAR(42) NOT NULL,
  UID_passegenr VARCHAR(42) NOT NULL,
  schedule      VARCHAR(42),
  start_place   VARCHAR(42),
  with_Comeback VARCHAR(42)
);

CREATE TABLE LEAGUE (
  PRIMARY KEY (UID),
  UID        VARCHAR(42) NOT NULL,
  start_date VARCHAR(42),
  end_date   VARCHAR(42)
);

CREATE TABLE PARTICIPATE (
  PRIMARY KEY (UID_1, UID_2),
  UID_1       VARCHAR(42) NOT NULL,
  UID_2       VARCHAR(42) NOT NULL,
  progression VARCHAR(42)
);

CREATE TABLE PLAY (
  PRIMARY KEY (UID_1, UID_2),
  UID_1      VARCHAR(42) NOT NULL,
  UID_2      VARCHAR(42) NOT NULL,
  experience VARCHAR(42)
);

CREATE TABLE STATISTIC (
  PRIMARY KEY (UID),
  UID          VARCHAR(42) NOT NULL,
  kilometers   VARCHAR(42),
  nb_carshares VARCHAR(42),
  CO_2_economy VARCHAR(42)
);

CREATE TABLE USER (
  PRIMARY KEY (UID),
  UID           VARCHAR(42) NOT NULL,
  pseudo        VARCHAR(42),
  password      VARCHAR(42),
  last_name     VARCHAR(42),
  first_name    VARCHAR(42),
  email         VARCHAR(42),
  company_ID    VARCHAR(42),
  car_type      VARCHAR(42),
  fuel          VARCHAR(42),
  level         VARCHAR(42),
  experience    VARCHAR(42),
  bonus_loyalty VARCHAR(42),
  UID_2         VARCHAR(42) NOT NULL,
  UID_3         VARCHAR(42) NOT NULL,
  UID_4         VARCHAR(42) NOT NULL,
  UNIQUE (UID_2)
);

ALTER TABLE CARSHARE ADD FOREIGN KEY (UID_driver) REFERENCES USER (UID);

ALTER TABLE ISPASSENGER ADD FOREIGN KEY (UID_passegenr) REFERENCES USER (UID);
ALTER TABLE ISPASSENGER ADD FOREIGN KEY (UID) REFERENCES CARSHARE (UID);

ALTER TABLE PARTICIPATE ADD FOREIGN KEY (UID_2) REFERENCES CHALLENGE (UID);
ALTER TABLE PARTICIPATE ADD FOREIGN KEY (UID_1) REFERENCES USER (UID);

ALTER TABLE PLAY ADD FOREIGN KEY (UID_2) REFERENCES LEAGUE (UID);
ALTER TABLE PLAY ADD FOREIGN KEY (UID_1) REFERENCES USER (UID);

ALTER TABLE USER ADD FOREIGN KEY (UID_4) REFERENCES COMPANY (UID);
ALTER TABLE USER ADD FOREIGN KEY (UID_3) REFERENCES USER (UID);
ALTER TABLE USER ADD FOREIGN KEY (UID_2) REFERENCES STATISTIC (UID);
